name: hola-proxy
version: '1.15.0'
summary: Standalone Hola proxy client.
description: |
  Standalone Hola proxy client. Just run it and it'll start plain HTTP proxy server forwarding traffic via Hola proxies of your choice.

confinement: strict
base: core18

parts:
  hola-proxy:
    plugin: go
    source: .
    build-packages:
      - gcc
    override-build:
      make &&
      cp bin/hola-proxy "$SNAPCRAFT_PART_INSTALL"
    stage:
      - hola-proxy

apps:
  hola-proxy:
    command: hola-proxy
    plugs:
      - network
      - network-bind
